services:
  head:
    image: crosscoders/ray/head:1.0
    container_name: ray-head

    build:
      context: .
      dockerfile: ray.Dockerfile
      args:
        - ACCELERATOR=gpu

    ports:
      - 8080:8080
      - 6379:6379
      - 8265:8265
      - 3000:3000

    # environment:
    #   - CONFIG_PATH=/app/src/config

    # volumes:
    #   - .:/app
      # - /app/node_modules # Prevent host node_modules from overwriting container's
