[project]
name = "crosscoders"
version = "0.1.0"
description = ""
# authors = [
#     { name = "", email = "" }
# ]

requires-python = ">=3.9"
license = { text = "MIT" }
readme = "README.md"

dynamic = ["dependencies", "optional-dependencies"]


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
dev = { file = ["requirements-dev.txt"] }
spark = { file = ["requirements-spark.txt"] }


[project.scripts]
xc = "scripts.main:main"


[build-system]
requires = ["setuptools"]   # ["setuptools>=66.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]
include = ["crosscoders"]