defaults:
  - base_config
  - dataset: tiny-stories
  - dataset/datasource: hf
  - language_model: tiny-stories-33M
  - batch: token
  - runner: data
  # - runner/training_objective: prediction
  - _self_




globals:
  local: true

batch:
  batch_size: 5
  # n_tokens: 100000
  n_records: 10

runner:
  strategy:
    _target_: crosscoders.strategies.data.TokensToActivationsStrategy

  # batch_size: 32  # laptop, 5.9GB VRAM for 0.0-activations
