defaults:
  - base_config
  - dataset: tiny-stories
  - dataset/datasource: hf
  - language_model: tiny-stories-33M
  - batch: sequence
  - runner: RayDataRunner
  - runner/training_objective: prediction
  - _self_



# # mandatory
# dataset:
#   name: ''
#   tag: ''

#   datasource:
#     which: ''
#     _target_: crosscoders.data.dataset.HuggingFaceDatasource._load

# language_model:
#   name: ''

# runner:
#   stage: ''
#   _target_: crosscoders.runners.data.ray.TokensToActivationsDataRunner
#   batch_size: 1

#   training_objective:
#     input_name: ''
#     output_name: ''


dataset:
  tag: tiny-stories-33M-1B


batch:
  batch_size: 150
  # n_tokens: 100000


runner:

  # batch_size: 32  # laptop, 5.9GB VRAM for 0.0-activations
  # max_tokens: 1000


  _target_: crosscoders.runners.data.ray.TokensToActivationsDataRunner