defaults:
  - _self_
  - base_config


# local: False
# s3_bucket: crosscoders
# dtype: float32
# device: cuda


# runner:
#   input_name: ln2.normalized
#   output_name: mlp_out


# paths:
#   # config_path: