defaults:
  - base_config
  - dataset/tinystories
  - runner/task/prediction
  - 0.0-activations
  # - 0.1-shuffle
  # - 0.2-statistics
  # - 1.0-train
  # - 2.0-eval
  - _self_


runner:

  batch_size: 32  # laptop, 5.9GB VRAM for 0.0-activations
  max_tokens: 1000
