

GLOBALS:

  EXPERIMENT:

    # # BATCH_SIZE: 30000
    # # BATCH_SIZE: 16384
    # BATCH_SIZE: 8192
    # # BATCH_SIZE: 1
    # # MAX_EPOCHS: 2
    # # MAX_RECORDS: 819200
    # # MAX_RECORDS: 300000
    # MAX_BATCHES: 10


    BATCH_SIZE: 16384
    # MAX_BATCHES:
    MAX_TOKENS: 1000000
    # MAX_TOKENS: 1000


    # no seqs - (batch_size * seq_len, n_layers, d_model)
    # BATCH_SIZE: 50000
    # MAX_RECORDS: 1000000

    # # seqs - (batch_size, seq_len, n_layers, d_model)
    # BATCH_SIZE: 12
    # MAX_RECORDS: 10000


RUNNER:

  INPUT_NAME: tiny-stories-33M.ln2.normalized
  OUTPUT_NAME: tiny-stories-33M.mlp_out


  MODEL:
    CAUSALITY: acausal
    ACTIVATION_FUNCTION: relu
    # eps: 2

    N_LAYERS: 4
    D_CODER: 24576


  # LOSS:
    # L1_COEFFICIENT: 0.2
    # L1_COEFFICIENT: 2
    # lambda_s: 10
    # lambda_p:
    # c: 4


  # OPTIMIZER:
  #   # optimizer: torch.optim.AdamW
  #   # optimizer: ${resolve_torch_optimizer:Adam}
  #   parameters:
      # lr: 0.002279
      # lr: 0.0002