


GLOBALS:

  PROJECT_ROOT_DIR: ~/repos/crosscoders
  CONFIG_FILEPATH:
  DATA_DIR: ~/repos/crosscoders/data


  EXPERIMENT:

    BATCH_SIZE: 50000
    MAX_EPOCHS: 1
    # MAX_TOKENS: 100000

    # MAX_RECORDS: 50000


RUNNER:
  MODEL:
    CAUSALITY: acausal